import React from 'react';
import { 
  ArrowLeft, Shield, Lock, FileText, Server, Cpu, Building2, CreditCard, RefreshCcw 
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function Policy() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-300 font-sans selection:bg-indigo-500/30">
      
      {/* --- HEADER --- */}
      <div className="fixed top-0 w-full z-50 bg-[#09090b]/80 backdrop-blur-md border-b border-white/5">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <button 
            onClick={() => navigate('/')} 
            className="flex items-center gap-2 text-sm font-medium text-zinc-400 hover:text-white transition-colors"
          >
            <ArrowLeft size={18} />
            Back to Home
          </button>
          <span className="font-bold text-white tracking-tight">CNEAPEE LEGAL CENTER</span>
        </div>
      </div>

      {/* --- CONTENT --- */}
      <main className="max-w-4xl mx-auto px-6 pt-32 pb-20">
        
        <div className="mb-12 text-center">
          <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-6 tracking-tight">
            Privacy Policy & <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
              Terms of Service
            </span>
          </h1>
          <p className="text-zinc-500 max-w-2xl mx-auto">
            Last Updated: December 2025. <br />
            Transparency is our core value. Below are our policies regarding data, payments, and usage.
          </p>
        </div>

        {/* --- SECTION 1: PRIVACY POLICY (OAuth & Data) --- */}
        <Section title="1. Privacy Policy & Data Handling" icon={Lock}>
          <p>
            At <strong>Cneapee.com</strong>, we prioritize your privacy. By using our platform, you agree to the collection and use of information in accordance with this policy.
          </p>
          
          <h3 className="text-white font-bold mt-6 mb-2">A. Google User Data (OAuth)</h3>
          <p>
            We use <strong>Google Sign-In</strong> for authentication. When you log in, we access only the following public information:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-zinc-400">
            <li><strong>Name:</strong> To personalize your experience.</li>
            <li><strong>Email Address:</strong> For account identification and communication.</li>
            <li><strong>Profile Picture:</strong> To display your avatar in the interface.</li>
          </ul>
          <div className="mt-4 p-4 bg-blue-500/10 border border-blue-500/20 rounded-lg text-sm text-blue-200">
            <strong>Important:</strong> We do <u>not</u> share your personal data with third parties or sell it to advertisers. Your data is strictly used for app functionality.
          </div>

          <h3 className="text-white font-bold mt-6 mb-2">B. AI Data Usage</h3>
          <p>
            Your text inputs and queries are processed by AI models (powered by Google Gemini).
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-zinc-400">
            <li>Do not share sensitive personal information (like credit cards, passwords, or health records) in your AI chats.</li>
            <li>Anonymized interactions may be used to improve model performance by our API providers.</li>
          </ul>
        </Section>

        {/* --- SECTION 2: AI DISCLAIMER --- */}
        <Section title="2. AI Disclaimer & Limitations" icon={Cpu}>
          <p>
            Cneapee utilizes advanced artificial intelligence (Google Gemini API) to generate text, code, and insights.
          </p>
          <h3 className="text-white font-bold mt-6 mb-2">Accuracy Warning</h3>
          <p>
            <strong>AI can make mistakes.</strong> Responses generated by Cneapee may differ from real-world facts. You should independently verify all information, especially regarding:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-zinc-400">
            <li>Medical advice (Health+ is for informational purposes only).</li>
            <li>Legal or financial advice.</li>
            <li>News accuracy (News+ aggregates data but cannot guarantee real-time truth).</li>
          </ul>
          <p className="mt-4">
            Cneapee is not liable for any actions taken based on the information provided by the AI.
          </p>
        </Section>

        {/* --- SECTION 3: TERMS OF SERVICE --- */}
        <Section title="3. Terms of Service" icon={FileText}>
          <p>By accessing Cneapee, you agree to abide by these terms:</p>
          <ul className="list-disc pl-5 mt-4 space-y-2 text-zinc-400">
            <li><strong>Age Restriction:</strong> By using Cneapee, you confirm that you are at least 18 years old.</li>
            <li><strong>Acceptable Use:</strong> You must not use the platform to generate illegal, harmful, threatening, or sexually explicit content.</li>
            <li><strong>Account Security:</strong> You are responsible for keeping your Google account secure. We are not liable for unauthorized access resulting from your negligence.</li>
            <li><strong>Service Availability:</strong> We strive for 99% uptime, but we do not guarantee uninterrupted access. We rely on third-party APIs (Google, GNews) which may experience outages.</li>
          </ul>
        </Section>

        {/* --- SECTION 4: PAYMENTS & REFUNDS (CRITICAL FOR GATEWAY) --- */}
        <Section title="4. Payments, Refunds & Cancellations" icon={CreditCard}>
          <p>
            This section outlines the terms for purchasing subscriptions (Student/Working/Coder plans) on Cneapee.
          </p>

          <h3 className="text-white font-bold mt-6 mb-2">A. Pricing & Payment</h3>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-zinc-400">
            <li>All prices listed on the Pricing page are in <strong>Indian Rupees (INR)</strong>.</li>
            <li>Payments are processed securely via third-party gateways (e.g., Easebuzz, Cashfree, UPI). We do not store your card details on our servers.</li>
          </ul>

          <h3 className="text-white font-bold mt-6 mb-2 text-red-400 flex items-center gap-2">
            <RefreshCcw size={18}/> B. Refund Policy
          </h3>
          <div className="p-4 bg-zinc-900 border border-zinc-700 rounded-lg text-sm">
            <p className="mb-2">
              <strong>Digital Goods Policy:</strong> Cneapee provides digital services (AI Tokens/Credits) which are consumed immediately upon usage. Therefore:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-zinc-400">
              <li><strong>General Rule:</strong> All sales are final. We do not offer refunds once a plan is purchased and the account status is updated to Pro/Student.</li>
              <li><strong>Exception (Technical Error):</strong> If money is deducted from your bank account but your Cneapee plan is <u>not updated</u> within 24 hours, you are eligible for a full refund. Please email us with your Transaction ID.</li>
              <li><strong>Refund Timeline:</strong> Eligible refunds will be processed within <strong>5-7 business days</strong> to the original payment method.</li>
            </ul>
          </div>

          <h3 className="text-white font-bold mt-6 mb-2">C. Cancellation Policy</h3>
          <p>
            You may cancel your subscription renewal at any time. Since Cneapee operates on a non-recurring (manual top-up) model for many plans, simply do not purchase the next month's plan to cancel.
          </p>
        </Section>

        {/* --- SECTION 5: API ATTRIBUTIONS --- */}
        <Section title="5. Third-Party Services & APIs" icon={Server}>
          <p>Cneapee is powered by incredible technologies. We acknowledge the use of:</p>
          <div className="grid gap-4 mt-4 sm:grid-cols-2">
            <div className="p-4 rounded-xl bg-zinc-900 border border-zinc-800">
              <div className="font-bold text-white mb-1">Google Gemini API</div>
              <div className="text-xs text-zinc-500">Used for Chatbot, Vision, and Text Generation.</div>
            </div>
            <div className="p-4 rounded-xl bg-zinc-900 border border-zinc-800">
              <div className="font-bold text-white mb-1">GNews API</div>
              <div className="text-xs text-zinc-500">Used for aggregating real-time news headlines.</div>
            </div>
          </div>
        </Section>

        {/* --- SECTION 6: LEGAL & ORGANIZATION STATUS --- */}
        <Section title="6. Legal & Organization Status" icon={Building2}>
          <div className="space-y-4">
            <div className="p-4 bg-green-900/10 border border-green-500/20 rounded-xl">
               <p className="text-green-100 font-medium">
                 Organization Status: Active
               </p>
            </div>
            <p>
              <strong>cneapee.com</strong> is operated as an <strong>Individual / Sole Proprietorship</strong> entity based in India. We are committed to operating in full compliance with local regulations.
            </p>
            <p className="text-sm text-zinc-500">
              *Note: For official inquiries or support requests, response may take upto 24hrs.
            </p>
          </div>
        </Section>

        {/* --- CONTACT & GRIEVANCE (DPDP COMPLIANCE) --- */}
        <div className="mt-12 pt-8 border-t border-white/10 text-center">
          <Shield className="mx-auto text-zinc-600 mb-4" size={32} />
          
          <h3 className="text-white font-bold mb-2">Contact & Grievance Redressal</h3>
          <p className="text-zinc-500 mb-4 max-w-lg mx-auto text-sm">
            In accordance with the Digital Personal Data Protection (DPDP) Act, 2023, 
            and Payment Settlement Act, the contact details are provided below:
          </p>
          
          <div className="inline-block text-left bg-zinc-900 p-6 rounded-2xl border border-zinc-800">
             <p className="text-zinc-400 text-sm">Business Entity: <span className="text-white font-bold">Individual (Sanskriti Bhushan)</span></p>
             <p className="text-zinc-400 text-sm mt-1">Domain: <span className="text-white">cneapee.com</span></p>
             <p className="text-zinc-400 text-sm mt-1">Location: <span className="text-white">Patna, Bihar, India</span></p>
             <hr className="my-3 border-zinc-800"/>
             <p className="text-zinc-400 text-sm mt-1">Support Email: <a href="mailto:support@cneapee.com" className="text-indigo-400 hover:underline">support@cneapee.com</a></p>
          </div>

          <p className="text-zinc-600 mt-8 text-xs">
              © 2025 Cneapee. All rights reserved.
          </p>
        </div>

      </main>
    </div>
  );
}

// Simple Helper Component for Sections
function Section({ title, icon: Icon, children }) {
  return (
    <section className="mb-12 relative group">
      <div className="absolute -inset-4 bg-gradient-to-r from-blue-500/5 to-purple-500/5 rounded-3xl opacity-0 group-hover:opacity-100 transition duration-500" />
      <div className="relative">
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-zinc-800 rounded-lg text-white">
            <Icon size={24} />
          </div>
          <h2 className="text-2xl font-bold text-white">{title}</h2>
        </div>
        <div className="leading-relaxed text-zinc-400 space-y-4">
          {children}
        </div>
      </div>
    </section>
  );
}